// Expo config plugin — pin the onnxruntime-android AAR to a concrete version.
//
// onnxruntime-react-native pulls `com.microsoft.onnxruntime:onnxruntime-android`
// at a DYNAMIC version (`latest.integration`), which forces a maven-metadata.xml
// listing that trips this JDK's XML parser (SAXNotRecognizedException:
// accessExternalSchema) and fails `extractLibs`. Forcing a concrete version makes
// Gradle fetch the POM directly and skip the broken metadata path. Must also
// match the cpp<->AAR pair shipped by the pinned npm package (1.20.0).
//
// This lives as a plugin (not a hand-edit of android/build.gradle) because
// android/ is gitignored and regenerated by `expo prebuild` — a manual edit
// would be wiped on every clean. Idempotent; harmless if the version already
// resolves concretely.
const { withProjectBuildGradle } = require("@expo/config-plugins");

const ORT_VERSION = "1.20.0";
const MARKER = "// [withOnnxRuntimePin]";

const SNIPPET = `
${MARKER}
allprojects {
    configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.microsoft.onnxruntime') {
                details.useVersion '${ORT_VERSION}'
            }
        }
    }
}
`;

module.exports = function withOnnxRuntimePin(config) {
  return withProjectBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== "groovy") {
      throw new Error("withOnnxRuntimePin: expected a groovy build.gradle");
    }
    if (!cfg.modResults.contents.includes(MARKER)) {
      cfg.modResults.contents += SNIPPET;
    }
    return cfg;
  });
};
